### ISSUE TITLE
Spotify HOSTS blocks all images

### ISSUE THREAD

**Issue by icedterminal** [CHEF-KOCH/CKs-FilterList#73] opened 2019-02-20 21:03 UTC
**Describe the site issue**
All images are blocked

### Test link
n/a

### Screenshot of the web page (_optional_)
![1](https://user-images.githubusercontent.com/4755734/53124020-3d419300-350f-11e9-8821-204641ede777.png)
![2](https://user-images.githubusercontent.com/4755734/53124026-403c8380-350f-11e9-95f6-1873175ae091.png)

### Screenshot of the developer console (**if possible**)
n/a

### Reproduction steps
*Starting with a clean hosts*
Copy the contents of `spotify-hosts.txt`
Paste into hosts and save
Open Spotify desktop
Images fail to load

### Environment specifications

- Filter list version: 0.0.24
- Operating system and version: Win 10 1809, Ubuntu 18.04, macOS 10.13.6
- Browser and version:n/a
- Adblocker and version:n/a
- Spotify: 1.1.0.237.g378f6f25
- Server: California, Mountain view

### Add any other additional helpful information (_optional_)
Cache and DNS cache cleared.

It appears this was brought up in /issues/43
I'm guessing the ticket I opened didn't suffice /issues/72

**Comment by CHEF-KOCH** [comment] 2019-02-20 21:11
_Almost_ a correct bug report, missing and the most important information is which server your Spotify client uses otherwise I'm not able to reproduce the issue and have to close it again. 

Swiss server(s) are working fine:
![wffwf](https://user-images.githubusercontent.com/727123/53124714-56246580-355c-11e9-9efc-67bb04591e57.png)

**Comment by icedterminal** [comment] 2019-02-20 21:39
Spotify: 1.1.0.237.g378f6f25
Server: California, Mountain view

**Closed** 2019-02-21 05:14 UTC
Labels: problem, resolved
